export const UPDATE_REMARK_DIALOGS = 'UPDATE_REMARK_DIALOGS';

export const DELETE_REMARK_DIALOGS = 'DELETE_REMARK_DIALOGS';

export const UPDATE_TRADERULE_REMARK = 'UPDATE_TRADERULE_REMARK';



