export const UPDATE_TRADE_RULES	 = 'UPDATE_TRADE_RULES';

export const UPDATE_REMARK_DIALOGS = 'UPDATE_REMARK_DIALOGS';

export const DELETE_REMARK_DIALOGS = 'DELETE_REMARK_DIALOGS';

export const UPDATE_TRADERULE_REMARK = 'UPDATE_TRADERULE_REMARK';

export const UPDATE_COPY_TO_NEW__GROUP_DIALOGS = 'UPDATE_COPY_TO_NEW__GROUP_DIALOGS';

export const DELETE_COPY_TO_NEW__GROUP_DIALOGS = 'DELETE_COPY_TO_NEW__GROUP_DIALOGS';

export const UPDATE_TRADERULE_TABLE = 'UPDATE_TRADERULE_TABLE';



